# Generated by Django 6.1.1 on 2026-10-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_c01_reservations(apps, schema_editor):
    Reservation = apps.get_model('reservation', 'Reservation')
    Allocation = apps.get_model('reservation', 'ReservationSeat')
    database = schema_editor.connection.alias
    for reservation in Reservation.objects.using(database).iterator():
        Allocation.objects.using(database).create(
            reservation_id=reservation.pk,
            performance_id=reservation.performance_id,
            seat_id=reservation.seat_id,
            active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('approve_reservation', 'Can approve or reject reservations')]},
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation_performance_seat',
        ),
        migrations.AddField(
            model_name='reservation',
            name='approval_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='CONFIRMED', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservationseat',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.performance'),
        ),
        migrations.AddField(
            model_name='reservationseat',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='reservationseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.seat'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.ManyToManyField(through='reservation.ReservationSeat', to='reservation.seat'),
        ),
        # Preserve original seat assignments before removing the old FK.
        # Reversal is intentionally unsupported: a multi-seat reservation cannot
        # be represented by the original single-seat schema without data loss.
        migrations.RunPython(preserve_c01_reservations),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PENDING_APPROVAL', 'CONFIRMED', 'CANCELLED', 'REJECTED', 'EXPIRED'])), name='valid_reservation_status'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), ('hold_until__isnull', False), _connector='OR'), name='draft_has_hold_deadline'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PENDING_APPROVAL'), _negated=True), ('approval_deadline__isnull', False), _connector='OR'), name='pending_has_approval_deadline'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.AddConstraint(
            model_name='reservationseat',
            constraint=models.UniqueConstraint(fields=('reservation', 'seat'), name='unique_seat_per_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservationseat',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('performance', 'seat'), name='unique_active_performance_seat'),
        ),
    ]
